### ISSUE TITLE
Metadatum Nachdrucke

### ISSUE THREAD

**Issue by haoess** [avh-bern-berlin/avh-texts#19]
Folgende Dokumente enthalten Fragezeichen im Metadatum für die Nachdrucke, kodiert via `<relatedItem type="reprint">`. Das sollte so nicht publik gehen.

1. 1799-Gelehrte_Reisen-1

*Memoiren Alexander von Humboldt’s. Bd. 1. Leipzig 1861, S. 36-38.<i></i><i>Memoiren Alexander von Humboldt’s.</i> 2. [Titel-]Aufl. 1864. [Soll diese zweite Auflage überhaupt auch angegenben werden?]
[Und: In den Jugendbriefen steht auf S. XXXV, dass die <i>Memoiren</i> eine Fälschung seien, zudem gibt folgender Artikel darüber Auskunft: http://www.uni-potsdam.de/romanistik/hin/hin22/biermann-schwarz.htm. Soll dieser posthume Nachweis also aus unserer Bibliographie gelöscht werden? Prüfen.]
<i>Die Jugendbriefe Alexander von Humboldts 1787–1799</i>, herausgegeben von Ilse Jahn und Fritz G. Lange, Berlin: Akademie 1973, S. 679;
Alexander von Humboldt, <i>Briefe aus Amerika 1799–1804</i>, herausgegeben von Ulrike Moheit, Berlin: Akademie 1993, S. 38–39.*

2. 1803-Extrait_de_plusieurs-05

*[Auszug] in: Humboldt. Correspondance inédite scientifique et littéraire, herausgegeben von Jean Bernard Marie Alexandre Dezos de La Roquette, 2 Bände, Paris: E. Ducrocq 1865/1869, Band 1, S.132-148 [Brief vom 25.11.1802 an Wilhelm Humboldt] ;
[Auszug] in: <i>Briefe Alexander’s von Humboldt an seinen Bruder Wilhelm</i>, hrsg. von der Familie von Humboldt in Ottmachau, Stuttgart 1880, S. 40-54 [Brief vom 25.11.1802 an Wilhelm Humboldt] [dt. Übersetzung];
[Auszug] in:<i> Lettres américaines d’Alexandre de Humboldt (1798–1807)</i>, précédées d’une Notice de J.–C. Delamétherie et suivies d’un choix de documents en partie inédits, publiés avec une introduction et des notes par le E.T. Hamy, Paris [1905], S. 127-139 [Brief vom 25.11.1802 an Wilhelm Humboldt];
[Auszug] in: <i>Alejandro de Humboldt. Cartas americanas.</i> Compilación, prólogo, notas y cronología Charles Minguet. Traducción Marta Traba, Caracas 1980,  S.  92-100 [Brief vom 25.11.1802 an Wilhelm Humboldt];
Alexander von Humboldt, <i>Briefe aus Amerika 1799–1804</i>, herausgegeben von Ulrike Moheit, Berlin: Akademie 1993, S. 173 [welcher Brief ist damit gemeint; Nr. 71 oder Nr. 72?], 187 und 199, S. 207–215 [Brief vom 25.11.1802 an Wilhelm Humboldt], S. 225, 252.*

3. 1831-xxx_Lettre_a_l-1-neu

*noch nicht abschließend geprüft (Möglichkeit einer Übersetzung in einer Briefedition?)*

4. 1835-xxx_Lettre_a_Francois-02-neu
*noch nicht abschließend geprüft (Möglichkeit einer Übersetzung in einer Briefedition?)*

5. 1837-Ueber_zwei_Versuche-01

*<i>Der Deutsche in der Landschaft</i>, herausgegeben von Rudolf Borchardt, München: Verlag der Bremer Presse 1927, S. 109–117.
als „Versuch den Gipfel des Chimborazo zu ersteigen“, in: <i>Berliner Zeitung</i> 301 (25. Dezember 1958), S. XXX;
Douglas Botting, <i>Alexander von Humboldt. Biographie eines großen Forschungsreisenden</i>, München 1974. S. 341–388. [Wiederabdruck] Englische Ausgabe auch?;
Alexander von Humboldt, <i>Mi viaje por el camino del inca (1801–1802)</i>, herausgegeben von David Yudilevich Levy, Santiago de Chile: Editorial Universitaria 2004, S. 193–208.
Alexander von Humboldt:<i> Ueber einen Versuch den Gipfel des Chimborazo zu ersteigen</i>, hrsg. v. Oliver Lubrich und Ottmar Ette, Berlin:Eichborn Berlin 2006, S. 153–181.
Alexander von Humboldt, <i>Das große Lesebuch</i>, herausgegeben von Oliver Lubrich, Frankfurt/M.: Fischer 2009, S. 196–220.*

**Comment by thomasnehrlich** [comment]
Ist inzwischen bereinigt.
