### ISSUE TITLE
Druckfehlerkorrekturen

### ISSUE THREAD

**Issue by haoess** [avh-bern-berlin/avh-texts#2]
Beispiel: https://avh.narek.dwds.de/text/1799-Alexander_von_Humboldt-1

Der Druckfehler "Hoſe" statt "Hofe" ist in der Druckausgabe (Bd. I, S. 459) korrigiert, hier (noch) nicht; sind diese Korrekturen in den Druckfahnen irgendwo gesammelt, um sie wiederum in digitale Ausgabe zurück übertragen zu können?

**Comment by thomasnehrlich** [comment]
Der Vorgang ist aus meiner Sicht grundsätzlich abgeschlossen.
