### ISSUE TITLE
DTA und Bern: Links ergänzen

### ISSUE THREAD

**Issue by cthomasdta** [avh-bern-berlin/avh-texts#25]
m.E. kann https://www.deutschestextarchiv.de/humboldt_meer_1833 verlinkt werden mit diesen beiden:

* https://humboldt.unibe.ch/text/1851-Sur_le_Gulf-1-neu
* https://humboldt.unibe.ch/text/1837-xxx_Ueber_Meeresstroeme-1

Habe ich im Spreadsheet schon ergänzt. Thomas, stimmst du zu?

**Comment by thomasnehrlich** [comment]
Sehr gern, vielen Dank für den Hinweis, ich habe die bibliographischen Angaben zur Entsprechung im (ungedruckten) Buchwerk bei beiden Dateien auch entsprechend noch ein bisschen überarbeitet.
