### ISSUE TITLE
Fehler Instrumentenverzeichnis: John vs. Pierre/Peter Dollond, falscher GND-Link

### ISSUE THREAD

**Issue by cthomasdta** [avh-bern-berlin/avh-texts#33]
https://humboldt.unibe.ch/erschliessung/instrumente_und_medien 

> **Fernrohr, Teleskop**
> […] Humboldt besaß ein achromatisches Fernrohr von [Peter Dollond](http://d-nb.info/gnd/117650390), […]

= Link geht auf http://d-nb.info/gnd/117650390, das ist ist aber John (Vater), nicht Peter (Sohn), der wäre https://d-nb.info/gnd/117650412.

Evtl. ist auch tatsächlich John gemeint, also der Text falsch und nicht der Link – oder es sind _beide_ gemeint und es sollte eher von der "Werkstatt" Dollond die Rede sein?

Bitte prüfen und ggfs. korrigieren, Lösung interessiert mich natürlich auch!

**Comment by thomasnehrlich** [comment]
Vielen Dank für den Hinweis! Ich nehme an, der Link wurde falsch gesetzt. Friedrich L. Brands "Alexander von Humboldts physikalische Meßinstrumente und Meßmethoden" scheints in der Schweiz nicht zu geben. Darauf basieren die Angaben ja großenteils, da müsste mans wohl prüfen. Du hast es nicht zufällig zur Hand? Sonst wäre ich vorläufig für Korrektur des Links, sodass wenigstens die richtige GND-ID hinterlegt ist. Häufig ist in diesen Fällen wahrscheinlich die Werkstatt gemeint, wie Du sagst. Aber dafür gibts keine Normdaten, oder?

**Comment by cthomasdta** [comment]
Brand kann ich dir schicken; es gibt auch noch ein ganz paar XML-Kommentare von mir in der Datei, die du bei der Gelegenheit gleich mit abgleichen kannst. 

> Werkstatt gemeint, wie Du sagst. Aber dafür gibts keine Normdaten, oder?

Richtig, das lässt sich doch aber gut durch Nennung der Personennamen und das Wort "Werkstatt" abfangen: Etwa "ein Instrument aus der Werkstatt von (Person|Link) und (Person|Link)".

**Comment by thomasnehrlich** [comment]
Super, danke für den Brand.
Deine Kommentare habe ich schon gesehen, aber bisher noch nicht abarbeiten können. Das sind aber natürlich sehr hilfreiche Hinweise. Die von Dir vorgeschlagene Umformulierung finde ich gut.

**Comment by thomasnehrlich** [comment]
Ich habe die Infos aus Brand (der zum Teil auch einfach die Instrumenten-Liste aus der "Relation historique, Band 1, S. 57–60 wiedergibt) gleich umgesetzt und dabei auch noch Fehler in dem Fernrohr-Eintrag im Glossar korrigieren und weitere Informationen eintragen können. Zu Caroché (Carochez, Carochet) und Cauchoix (Cauchois) scheint es keine GND-Einträge zu geben.

**Comment by cthomasdta** [comment]
> Zu Caroché (Carochez, Carochet) und Cauchoix (Cauchois) scheint es keine GND-Einträge zu geben.

alternativ, bzw. in Ermangelung der GND, kannst du aber auf die ehd verweisen: 

```XML
<persName ref="https://edition-humboldt.de/H0012907">Noël-Simon Caroché</persName>
<persName ref="https://edition-humboldt.de/H0012955">Robert-Aglaé Cauchoix</persName>
```

**Comment by thomasnehrlich** [comment]
Hab ich jetzt mal gemacht, danke.

**Comment by cthomasdta** [comment]
Issue kann zu, ne? Ich leg gleich mal ein neues an, mit Ergänzungsvorschlägen, das fortlaufend geführt werden kann.
