### ISSUE TITLE
Update nach Commits

### ISSUE THREAD

**Issue by thomasnehrlich** [avh-bern-berlin/avh-texts#34]
Die Aktualisierung der Online-Edition nach Änderungen von XML-Dateien auf GitHub läuft grundsätzlich super.
In diesen beiden Fällen wird das Update aber nicht korrekt umgesetzt:
https://github.com/avh-bern-berlin/avh-texts/commit/7849a9763c7e4d8152a199200ef0e0483acde711
https://github.com/avh-bern-berlin/avh-texts/commit/345cc6f1b6344af108522b1383502e782c343dbb

Es handelt sich jeweils um bibliographische Korrekturen im Header. Sie werden weder in der Bibliographie auf der Startseite der Digitalausgabe noch in den Infoboxen im Textviewer angezeigt.
Oder liegt der Fehler bei mir?

**Comment by haoess** [comment]
Hm, komisch. Nach manuellem Restart der Web-Application werden die Daten nun korrekt angezeigt. Muss ich mal beobachten, das.

**Comment by thomasnehrlich** [comment]
Danke für die Erledigung!

**Comment by thomasnehrlich** [comment]
Die gestrigen Commits, die zum Teil auch bibliographische Angaben im Header betrafen, wurden nun korrekt umgesetzt.
