### ISSUE TITLE
Leerzeichenhandling

### ISSUE THREAD

**Issue by cthomasdta** [avh-bern-berlin/avh-texts#4]
https://avh.narek.dwds.de/text/1803-Extrait_de_plusieurs-10:

> ſehr genaue Beſchreibungenvom Ka ï man oder

```xml
&#x017F;ehr genaue Be&#x017F;chreibungen<lb break="yes"/>vom <hi rendition="#fr">Ka</hi>
                    <hi rendition="#aq">&#x00EF;</hi>
                    <hi rendition="#fr">man</hi> oder
```

Hier rutschen also Zeilenumbrüche rein, die dann wiederum zum Leerzeichenfehler führen. Ich kann ohne die Ausgangsdateien schlecht sagen, wie man das systematisch Suchen & Beheben könnte.

[edit: formatting]

**Comment by thomasnehrlich** [comment]
Ist inzwischen geklärt, soweit ich weiß.
