### ISSUE TITLE
error with II.37 1805-xxx_Preface_de_Plantes-1-neu.xml

### ISSUE THREAD

**Issue by rexclark2** [avh-bern-berlin/avh-texts#42]
@thomasnehrlich @haoess 

II.37 1805-xxx_Preface_de_Plantes-1-neu.xml 
is wrongly labeled II.36 and is bunched together with
II.36 1805-xxx_Note_sur_des-01-etc
so it doesn't exist as separate text, II.37 not findable. 

I'm not sure if xml file just needs editing, or some bibliographie files as well? 

Thanks

`<idno>
<idno type="print">II.36</idno>
<idno type="basename">1805-xxx_Preface_de_Plantes-1-neu</idno>
<idno type="type">secondary</idno>
</idno>
</publicationStmt>
<notesStmt>
<relatedItem target="1805-xxx_Note_sur_des-01-neu.xml" type="primary"/>
<relatedItem target="1805-xxx_Note_sur_des-02-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-03-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-04-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-05-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-06.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-07-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-08-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-09-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-10-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Note_sur_des-11-neu.xml" type="secondary"/>
<relatedItem target="1805-xxx_Preface_de_Plantes-1-neu.xml" type="self"/>
</notesStmt>`

**Comment by haoess** [comment]
> I'm not sure if xml file just needs editing, or some bibliographie files as well?

No, all bibliographic information used for display is extracted right off the XML files. So, for changing things related to `II.36`, these files have to be looked at:

* 1805-xxx_Note_sur_des-01-neu.xml
* 1805-xxx_Note_sur_des-02-neu.xml
* 1805-xxx_Note_sur_des-03-neu.xml
* 1805-xxx_Note_sur_des-04-neu.xml
* 1805-xxx_Note_sur_des-05-neu.xml
* 1805-xxx_Note_sur_des-06.xml
* 1805-xxx_Note_sur_des-07-neu.xml
* 1805-xxx_Note_sur_des-08-neu.xml
* 1805-xxx_Note_sur_des-09-neu.xml
* 1805-xxx_Note_sur_des-10-neu.xml
* 1805-xxx_Note_sur_des-11-neu.xml
* 1805-xxx_Preface_de_Plantes-1-neu.xml

**Comment by rexclark2** [comment]
Great, as it should be, I did edits, all fixed now, thanks for the help!
