### ISSUE TITLE
1809-Geografia_de_las-1-neu.xml

### ISSUE THREAD

**Issue by rexclark2** [avh-bern-berlin/avh-texts#9]
@thomasnehrlich @Grimnir7 

Low priority, but putting things into the repository. I got a modern 1966 edition of Caldas text and much better OCR came through even with some of the table structure. Appended this to existing text, did rough edits up through original p. 165. Leaving it here for further cleanup as we have time. So ignore any other texts I sent. 

Also the Gesamtbiblio will need updating to this, new text bolded:

Semanario del Nuevo Reyno de Granada 16 (23. April 1809), S. 127–128; 17 (30. April 1809), S. 129–136; 18 (7. Mai 1809), S. 137–[144]; 19 (14. Mai 1809), S. 145–152; 20 (21. Mai 1809), S. 153–160; 21 (28. Mai 1809), S. 161–**168, 22 (4. Juni 1809), S. 169–176, 23 (11. Juni 1809), S. 177–184, 24 (18. Juni 1809), S. 185–189.**

Also, are we trying to keep the pdf files up to date? If so the pdf needs to be updated from the K1809-Geografia to include the added Caldas "Notas".

**Comment by thomasnehrlich** [comment]
Ist inzwischen bereinigt.
